name: Run the tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ui-tests:
    strategy:
      fail-fast: false
      matrix:
        shard: [1/4, 2/4, 3/4, 4/4]
    runs-on: ubuntu-latest

    steps:
      - name: Check out project
        uses: actions/checkout@v5

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "18"

      - name: Clean install the project
        run: npm ci

      - name: Install Playwright
        run: npx playwright install

      - name: Run UI Playwright tests
        env:
          SLACK_BOT_USER_OAUTH_TOKEN: ${{ secrets.SLACK_BOT_USER_OAUTH_TOKEN }}
        run: npx playwright test --shard ${{ matrix.shard }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-ui-${{ matrix.shard }}
          path: playwright-report/
          retention-days: 30

  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out project
        uses: actions/checkout@v5

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "18"

      - name: Clean install the project
        run: npm ci

      - name: Install Playwright
        run: npx playwright install

      - name: Run API Playwright tests
        env:
          SLACK_BOT_USER_OAUTH_TOKEN: ${{ secrets.SLACK_BOT_USER_OAUTH_TOKEN }}
        run: npx playwright test --config=api.config.ts tests/api.spec.ts

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-api
          path: playwright-report/
          retention-days: 30